### ISSUE TITLE
[Bug] Crash budgie-desktop after 2024.git update from backports

### ISSUE THREAD

**Issue by kbruno89** [BuddiesOfBudgie/budgie-desktop#511] opened 2024-01-28 12:03 UTC
### Description

After update budgie-desktop from backports (version 10.8.2 2024.git), desktop wont load anymore.

Put password and back to login screen.

First, get issues with "has_option" function wont be sourced...

After workaround, get another error:  /usr/bin/budgie-desktop: 16: exec: budgie-session: not found

### Budgie version

10.8.2 2024.git

### Operating System

Ubuntu Budgie 23.10

### Steps to reproduce the issue

1. Put password in login screen
2. Desktop dont load, back to login screen

### Actual result

/usr/bin/budgie-desktop: 16: exec: budgie-session: not found

### Expected result

budgie-session start

**Comment by JoshStrobl** [comment] 2024-01-28 12:37
I'm going to close this issue as this is expected behavior. Budgie Desktop for 10.9 introduces the requirement for budgie-session to be packaged by the respective operating system. @fossfreedom will be packaging budgie-session for Debian (and Ubuntu) for its use with current Budgie.

It is not intended for non-developers to use any form of git builds of budgie-desktop.

**Closed by JoshStrobl** 2024-01-28 12:37 UTC

**Comment by kbruno89** [comment] 2024-01-28 13:39
Hi,

How to revert this?

Please disable PPA budgie-desktop-test to avoid this for another users...

Em dom., 28 de jan. de 2024 09:37, Joshua Strobl ***@***.***>
escreveu:

**Comment by fossfreedom** [comment] 2024-01-28 14:03
@kbruno89 update in about an hours time - budgie-session will be available in that PPA

You should note that this is a developers test PPA - breakages are expected

If you want a stable system you should purge that PPA

    sudo ppa-purge ppa:ubuntubudgie-dev/budgie-desktop-test

**Comment by kbruno89** [comment] 2024-01-28 14:07
Ok, thanks for the update.

After update and fix, i will disable this ppa.

Enabled before only to get 10.8.2.

Em dom., 28 de jan. de 2024 11:03, David Mohammed ***@***.***>
escreveu:
