### ISSUE TITLE
Some custom keyboard shortcut combinations stop working after rebooting

### ISSUE THREAD

**Issue by locque** [BuddiesOfBudgie/budgie-desktop#35] opened 2022-01-14 10:50 UTC
## Description
Some custom keyboard shortcut combinations like `super`+`o` stop working after rebooting.

## Budgie version
10.5.3

## Operating system
Arch

## Steps to reproduce the issue
- Open keyboard settings in gnome control center
- Create custom shortcut
- Set some kind of basic command and the combination to  `super`+`o`
- Check if the command works
- Reboot
- Command does not get executed by the shortcut anymore, even though it is still listed in the keyboard settings

## Actual result
- Shortcut is broken after rebooting, has to be manually fixed by opening the keyboard settings and entering the shortcut for that command again

## Expected result
- Shortcut should still work after rebooting

**Comment by locque** [comment] 2022-01-14 11:59
```
Jan 14 12:48:58 tiny gnome-session[547]: gnome-session-binary[547]: WARNING: Could not parse desktop file budgie-desktop-nm-applet.desktop or it references a not found TryExec binary
Jan 14 12:48:58 tiny gnome-session-binary[547]: WARNING: Could not parse desktop file budgie-desktop-nm-applet.desktop or it references a not found TryExec binary
Jan 14 12:48:58 tiny gnome-session[547]: gnome-session-binary[547]: WARNING: Could not parse desktop file budgie-desktop-screensaver.desktop or it references a not found TryExec binary
Jan 14 12:48:58 tiny gnome-session-binary[547]: WARNING: Could not parse desktop file budgie-desktop-screensaver.desktop or it references a not found TryExec binary
Jan 14 12:48:59 tiny budgie-wm[722]: Running Mutter(Budgie) (using mutter 41.3) as a X11 window and compositing manager
Jan 14 12:48:59 tiny budgie-wm[722]: ibus.vala:47: ibus-daemon unsupported on this system
Jan 14 12:48:59 tiny dbus-daemon[552]: [session uid=1000 pid=552] Activating via systemd: service name='ca.desrt.dconf' unit='dconf.service' requested by ':1.33' (uid=1000 pid=722 comm="budgie-wm ")
Jan 14 12:49:00 tiny polkitd[417]: Registered Authentication Agent for unix-session:2 (system bus name :1.49 [budgie-polkit-dialog], object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.utf8)
Jan 14 12:49:00 tiny budgie-wm.desktop[722]: Window manager warning: Overwriting existing binding of keysym ff61 with keysym ff61 (keycode 6b).
Jan 14 12:49:00 tiny budgie-wm.desktop[722]: Window manager warning: Overwriting existing binding of keysym ff61 with keysym ff61 (keycode 6b).
Jan 14 12:49:00 tiny budgie-wm.desktop[722]: Window manager warning: Overwriting existing binding of keysym ff61 with keysym ff61 (keycode 6b).
Jan 14 12:49:01 tiny dbus-daemon[552]: [session uid=1000 pid=552] Connection :1.64 (uid=1000 pid=996 comm="dbus-monitor --profile interface='org.budgie_deskt") became a monitor.
Jan 14 12:49:01 tiny budgie-wm.desktop[722]: Window manager warning: Overwriting existing binding of keysym ff61 with keysym ff61 (keycode 6b).
Jan 14 12:49:01 tiny budgie-wm.desktop[722]: Window manager warning: Overwriting existing binding of keysym ff61 with keysym ff61 (keycode 6b).
Jan 14 12:49:01 tiny budgie-wm.desktop[722]: Window manager warning: Overwriting existing binding of keysym ff61 with keysym ff61 (keycode 6b).
Jan 14 12:49:01 tiny budgie-wm.desktop[722]: Window manager warning: Overwriting existing binding of keysym ff61 with keysym ff61 (keycode 6b).
Jan 14 12:49:01 tiny budgie-wm.desktop[722]: Window manager warning: Overwriting existing binding of keysym ff61 with keysym ff61 (keycode 6b).
Jan 14 12:49:01 tiny budgie-wm.desktop[722]: Window manager warning: Overwriting existing binding of keysym ff61 with keysym ff61 (keycode 6b).
Jan 14 12:49:01 tiny budgie-wm.desktop[722]: Window manager warning: Overwriting existing binding of keysym ff61 with keysym ff61 (keycode 6b).
Jan 14 12:49:01 tiny budgie-wm.desktop[722]: Window manager warning: Overwriting existing binding of keysym ff61 with keysym ff61 (keycode 6b).
Jan 14 12:49:01 tiny budgie-wm.desktop[722]: Window manager warning: Overwriting existing binding of keysym ff61 with keysym ff61 (keycode 6b).
Jan 14 12:49:01 tiny budgie-wm.desktop[722]: Window manager warning: Overwriting existing binding of keysym ff61 with keysym ff61 (keycode 6b).
Jan 14 12:49:01 tiny budgie-wm.desktop[722]: Window manager warning: Overwriting existing binding of keysym ff61 with keysym ff61 (keycode 6b).
Jan 14 12:49:01 tiny budgie-wm.desktop[722]: Window manager warning: Overwriting existing binding of keysym ff61 with keysym ff61 (keycode 6b).
Jan 14 12:49:02 tiny budgie-wm.desktop[722]: Window manager warning: Overwriting existing binding of keysym ff61 with keysym ff61 (keycode 6b).
Jan 14 12:49:02 tiny budgie-wm.desktop[722]: Window manager warning: Overwriting existing binding of keysym ff61 with keysym ff61 (keycode 6b).
Jan 14 12:49:02 tiny budgie-wm.desktop[722]: Window manager warning: Overwriting existing binding of keysym ff61 with keysym ff61 (keycode 6b).
Jan 14 12:49:02 tiny budgie-wm.desktop[722]: Window manager warning: Overwriting existing binding of keysym ff61 with keysym ff61 (keycode 6b).
Jan 14 12:49:02 tiny budgie-wm.desktop[722]: Window manager warning: Overwriting existing binding of keysym ff61 with keysym ff61 (keycode 6b).
Jan 14 12:49:02 tiny budgie-wm.desktop[722]: Window manager warning: Overwriting existing binding of keysym ff61 with keysym ff61 (keycode 6b).
Jan 14 12:49:03 tiny budgie-wm.desktop[722]: Window manager warning: Overwriting existing binding of keysym ff61 with keysym ff61 (keycode 6b).
Jan 14 12:49:03 tiny budgie-wm.desktop[722]: Window manager warning: Overwriting existing binding of keysym ff61 with keysym ff61 (keycode 6b).
Jan 14 12:49:03 tiny budgie-wm.desktop[722]: Window manager warning: Overwriting existing binding of keysym ff61 with keysym ff61 (keycode 6b).
```

Sure looks like something is overwriting it. What could be causing that? I didn't change anything from the default budgie install on arch.

**Comment by fossfreedom** [comment] 2022-01-14 12:50
Its probably an underlying arch issue - a change in impacts budgie.

The area of code are in the area here https://github.com/BuddiesOfBudgie/budgie-desktop/blob/f9cfa8e62232daee6e0b0ba2a6b85889e9f58910/src/wm/shim.vala#L187 - and related functions below that.

Since I don't use/run arch I cannot help further - but I would suggest adding debugging statements around this code area could be used to find out what is happening.

**Comment by serebit** [comment] 2022-03-20 14:48
Does this still happen for you on v10.6? We haven't made any changes to shim.vala for v10.6, but we can no longer easily test v10.5.3, so I want to make sure that it's at least still reproducible on your end before I start investigating.

**Comment by astahjmo** [comment] 2022-03-28 14:32
> 

in 10,6 still happen

budgie version
```[astaroth@tatsuki ~]$ budgie-desktop --version
budgie-desktop 10.6
Copyright © 2014-2022 Budgie Desktop Developers
```
journalctl -ae | grep -i budgie

```bash
[astaroth@tatsuki ~]$ journalctl -ae | grep -i budgie
Mar 28 11:05:12 tatsuki gnome-session[561]: gnome-session-binary[561]: WARNING: Could not parse desktop file budgie-desktop-screensaver.desktop or it references a not found TryExec binary
Mar 28 11:05:12 tatsuki gnome-session-binary[561]: WARNING: Could not parse desktop file budgie-desktop-screensaver.desktop or it references a not found TryExec binary
Mar 28 11:05:12 tatsuki gnome-session[561]: gnome-session-binary[561]: WARNING: Could not parse desktop file budgie-desktop-nm-applet.desktop or it references a not found TryExec binary
Mar 28 11:05:12 tatsuki gnome-session-binary[561]: WARNING: Could not parse desktop file budgie-desktop-nm-applet.desktop or it references a not found TryExec binary
Mar 28 11:05:20 tatsuki budgie-wm[765]: Running Mutter(Budgie) (using mutter 41.5) as a X11 window and compositing manager
Mar 28 11:05:21 tatsuki budgie-wm[765]: ibus.vala:47: ibus-daemon unsupported on this system
Mar 28 11:05:21 tatsuki dbus-daemon[565]: [session uid=1000 pid=565] Activating via systemd: service name='ca.desrt.dconf' unit='dconf.service' requested by ':1.37' (uid=1000 pid=765 comm="budgie-wm")
Mar 28 11:05:23 tatsuki budgie-wm.desktop[765]: Window manager warning: Overwriting existing binding of keysym ff61 with keysym ff61 (keycode 6b).
Mar 28 11:05:24 tatsuki budgie-panel[780]: notifications_view.vala:154: Unable to connect to notifications dispatcher: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.budgie_desktop.Notifications was not provided by any .service files
Mar 28 11:05:24 tatsuki polkitd[466]: Registered Authentication Agent for unix-session:2 (system bus name :1.47 [budgie-polkit-dialog], object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8)
Mar 28 11:05:42 tatsuki budgie-panel.desktop[984]: touch: cannot touch '/home/astaroth/.local/share/icons/hicolor/.xdg-icon-resource-dummy': No such file or directory
Mar 28 11:05:52 tatsuki budgie-wm[765]: Can't update stage views actor <unnamed>[<MetaStage>:0x5594bacbf570] is on because it needs an allocation.
Mar 28 11:05:52 tatsuki budgie-wm[765]: Can't update stage views actor <unnamed>[<MetaWindowGroup>:0x5594bae242f0] is on because it needs an allocation.
Mar 28 11:05:52 tatsuki budgie-wm[765]: Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x5594bade6f00] is on because it needs an allocation.
Mar 28 11:05:52 tatsuki budgie-wm[765]: Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x5594badf4db0] is on because it needs an allocation.
Mar 28 11:13:35 tatsuki budgie-panel.desktop[962]: malloc(): unsorted double linked list corrupted
Mar 28 11:14:13 tatsuki budgie-panel.desktop[1415]: Discord 0.0.17
Mar 28 11:14:14 tatsuki budgie-panel.desktop[1415]: Starting app.
Mar 28 11:14:14 tatsuki budgie-panel.desktop[1415]: Starting updater.
Mar 28 11:14:14 tatsuki budgie-panel.desktop[1415]: [Modules] Modules initializing
Mar 28 11:14:14 tatsuki budgie-panel.desktop[1415]: [Modules] Distribution: remote
Mar 28 11:14:14 tatsuki budgie-panel.desktop[1415]: [Modules] Host updates: enabled
Mar 28 11:14:14 tatsuki budgie-panel.desktop[1415]: [Modules] Module updates: enabled
Mar 28 11:14:14 tatsuki budgie-panel.desktop[1415]: [Modules] Module install path: /home/astaroth/.config/discord/0.0.17/modules
Mar 28 11:14:14 tatsuki budgie-panel.desktop[1415]: [Modules] Module installed file path: /home/astaroth/.config/discord/0.0.17/modules/installed.json
Mar 28 11:14:14 tatsuki budgie-panel.desktop[1415]: [Modules] Module download path: /home/astaroth/.config/discord/0.0.17/modules/pending
Mar 28 11:14:18 tatsuki budgie-panel.desktop[1415]: [Modules] No updates to install
Mar 28 11:14:18 tatsuki budgie-panel.desktop[1415]: [Modules] Checking for host updates.
Mar 28 11:14:19 tatsuki budgie-panel.desktop[1415]: [Modules] Host is up to date.
Mar 28 11:14:19 tatsuki budgie-panel.desktop[1415]: [Modules] Checking for module updates at https://discord.com/api/modules/stable/versions.json
Mar 28 11:14:19 tatsuki budgie-panel.desktop[1415]: [Modules] No module updates available.
Mar 28 11:14:19 tatsuki budgie-panel.desktop[1415]: Module ./ElectronTestRpc was not included.
Mar 28 11:14:19 tatsuki budgie-panel[780]: Encountered X error 1 when setting background for tray icon
Mar 28 11:20:23 tatsuki budgie-wm.desktop[765]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x360002c
Mar 28 11:22:43 tatsuki budgie-panel.desktop[1665]: ###!!! [Parent][PBackgroundParent] Error: RunMessage(msgname=PBroadcastChannel::Msg_Close) Channel closing: too late to send/recv, messages will be lost
Mar 28 11:26:51 tatsuki budgie-wm.desktop[765]: Window manager warning: WM_TRANSIENT_FOR window 0x1a0002c for override-redirect window 0x1a0434f is an override-redirect window and this is not correct according to the standard, so we'll fallback to the root window.
Mar 28 11:26:52 tatsuki budgie-wm.desktop[765]: Window manager warning: WM_TRANSIENT_FOR window 0x1a0002c for override-redirect window 0x1a0434f is an override-redirect window and this is not correct according to the standard, so we'll fallback to the root window.
```

**Comment by fossfreedom** [comment] 2022-03-28 14:41
You don't have budgie-screensaver installed. This will prevent full initialisation of gnome session 

Also you don't appear to have network-manager installed. Very odd.

These should all be dependencies in your distro packaging. This needs to be resolved with your distro package maintainer.

**Closed** 2022-03-28 16:08 UTC
Labels: bug, question
