### ISSUE TITLE
full desktop crush after adding widgets

### ISSUE THREAD

**Issue by RoraHarvest** [BuddiesOfBudgie/budgie-desktop#500] opened 2023-12-25 19:52 UTC
### Description

after attempting to add two widgets to my taskbar budgie completely crushed, exciting to a white fullscreen with A "fatal error from which budgie was unable to recover with only the option to log out. on farther logins the desktop would immediately crush to the same screen upon loading

### Budgie version

10.8.2

### Operating System

fedora 39 kde spin

### Steps to reproduce the issue

install budgie on a fedora spin other then its own (used kde with the wayland session)

open the panel configuration tool

add one widget (added the capslock inductor)

ad a second widget (attempted to add the keyboard layout widget)

desktop crush 

### Actual result

fullscreen white crush massage 

![IMG20231225214257](https://github.com/BuddiesOfBudgie/budgie-desktop/assets/125197603/e7c90417-b93c-41d0-9d32-fb39e9499612)
![IMG20231225214305](https://github.com/BuddiesOfBudgie/budgie-desktop/assets/125197603/c6d4d223-20e2-47a6-8e33-14af9480eda2)

the massage says: 
"oi, something went wrong
an error occurred and the system cannot recover.
please exit and try again" 
and a log out button

### Expected result

widget added

### Additional information

hardware: lenovo LOQ 16IRH8
Processor 	
13th Generation Intel® Core™ i7-13620H Processor (E-Core Max 3.60 GHz, P-Core Max 4.90 GHz with Turbo Boost, 10 Cores, 16 Threads, 24 MB Cache)

Operating System 	
    Windows 10
    Fedora 39 kde
  
Graphics 
 NVIDIA® GeForce RTX™ 4060 Laptop GPU, 8GB GDDR6

Memory 	
16GB 5200MHz DDR5
Storage 	
1TB NVMe M.2 Gen 4
1TB NVMe M.2 Gen 3

**Comment by JoshStrobl** [comment] 2023-12-27 07:10
Duplicate of #319

**Closed by JoshStrobl** 2023-12-27 07:10 UTC
