### ISSUE TITLE
[Request] Super key to open programs in task bar. 

### ISSUE THREAD

**Issue by androidnisse** [BuddiesOfBudgie/budgie-desktop#548] opened 2024-03-10 06:19 UTC
### Budgie version

10.9.1

### Use-cases

In Windows when you press the super key+1-9 the pinned program on that spot in the taskbar opens or you change to it if it is already open. In budgie nothing happens when you do this. Now when you want to open a program in the taskbar or change to one on a specific place you have to click on it with the mouse. To add this feature in budgie would save a lot of mouse clicking.

### References

I opened an request for this when Solus was the developer of Budgie.
https://github.com/solus-project/budgie-desktop/issues/1076

**Comment by JoshStrobl** [comment] 2024-03-10 19:39
Duplicate of #34

**Closed by JoshStrobl** 2024-03-10 19:39 UTC
