### ISSUE TITLE
Workspace Switcher icons size incorrectly with the French locale

### ISSUE THREAD

**Issue by fossfreedom** [BuddiesOfBudgie/budgie-desktop#240] opened 2022-12-28 23:25 UTC
## Description
Raised from our forum
https://discourse.ubuntubudgie.org/t/22-10-workspace-switcher-applet-and-item-size/6402

Any region where the decimal separator is a comma (not a full-stop / period) such as French causes the work-spacer switcher icon resizing to misbehave

## Budgie version
10.6.4 as well as the current big-sexy branch

## Operating system
Ubuntu Budgie 22.10

## Steps to reproduce the issue
In budgie-control-center - Region and Language - Formats - set to French
In BDS - panel - workspace switcher change the multiplier size - icons can disappear, or appear unaffected by the multiplier size change

## Actual result
![image](https://user-images.githubusercontent.com/996240/209884293-02760744-edc0-47d9-9f76-8623175e13fb.png)
icons with standard 1x multiplier

![image](https://user-images.githubusercontent.com/996240/209884316-6668555c-22ec-4979-8af6-ad6e2d42a0d2.png)
(icons disappear)

![image](https://user-images.githubusercontent.com/996240/209884331-f38e622f-5042-4028-88c1-2d0a6b2aad73.png)
(icons doesnt appear to resize)

## Expected result
Work correctly as for en based region formats

**Comment by serebit** [comment] 2022-12-29 05:27
Reproduced by @fossfreedom on both master and big-sexy. Marking as verified.

**Comment by serebit** [comment] 2022-12-29 18:05
Okay, so the issue is that `float.parse` changes its behavior depending on the current locale. French uses commas for decimal separators, so when it sees the string `0.75` (as an example), the function gets confused and just resolves it to zero, which breaks sizing. The same thing happens for all settings other than `1.0`. Easy enough to fix.

**Closed** 2022-12-29 21:14 UTC
Labels: bug, verified
