### ISSUE TITLE
mpv no longer appears in my taskbar

### ISSUE THREAD

**Issue by solomongrundy6** [BuddiesOfBudgie/budgie-desktop#113] opened 2022-04-19 04:24 UTC
Ever since the April 11th Solus update that updated budgie-desktop from 10.6 to 10.6.1, mpv will no longer appear in my taskbar.  Even if I pin mpv to the taskbar, it still does not recognize that mpv windows are open.  Additionally, when minimizing an mpv window that is open, the minimize animation goes to the top left of the screen instead of down to the taskbar.

**Comment by JoshStrobl** [comment] 2022-04-19 06:16
Duplicate of #105

**Closed by JoshStrobl** 2022-04-19 06:16 UTC
