### ISSUE TITLE
Vertical panel issues with maximized windows

### ISSUE THREAD

**Issue by ghost** [BuddiesOfBudgie/budgie-desktop#32] opened 2022-01-09 21:36 UTC
Sometimes when configuring the Budgie panel in vertical mode, maximized windows overlap the panel, or vice-versa. For me, the icons and panel elements seem to perfectly line up only when the icon size is set to exactly 53, where the icons abruptly jump in size. (I have a top panel in the screenshots but this doesn't affect the issues with the vertical panel)
It could be that the window manager strut doesn't match actual panel/icon size
![Screenshot from 2022-01-09 15-33-53](https://user-images.githubusercontent.com/97410614/148701817-55b2ddaa-9422-4a2e-81e4-84d1f728fbc4.png)
![Screenshot from 2022-01-09 15-34-11](https://user-images.githubusercontent.com/97410614/148701838-6c035aca-0deb-4afa-aad6-9b618016b914.png)

**Comment by JoshStrobl** [comment] 2022-01-10 07:50
> where the icons abruptly jump in size

Duplicate of #25 in that particular case. Can't follow-up with user because they deleted their account so :shrug:

**Comment by serebit** [comment] 2022-03-19 20:45
This should be fixed as of some panel-related commits that made it into v10.6, so I'm closing the issue. If anyone is still seeing this, feel free to comment and I'll reopen it.

**Closed by serebit** 2022-03-19 20:45 UTC
Labels: bug
