### ISSUE TITLE
[Bug]  file to customize the application menu is missing

### ISSUE THREAD

**Issue by ATMB758** [BuddiesOfBudgie/budgie-desktop#604] opened 2024-08-27 12:22 UTC
### Description

In case of crowded application menu with a lot of applications in one category, it would be handy to add subcategories to the application menu to combine several application. The file to customize the application menu is missing: https://specifications.freedesktop.org/menu-spec/latest/paths.html

### Budgie version

10.9.2

### Operating System

Arch Linux

### Steps to reproduce the issue

No application.menu file in /etc/xdg/menu

### Actual result

No application.menu file in /etc/xdg/menu

### Expected result

Available .menu file as described in https://specifications.freedesktop.org/menu-spec/latest/paths.html

**Comment by JoshStrobl** [comment] 2024-08-28 06:19
Duplicate of #506

**Closed by JoshStrobl** 2024-08-28 06:19 UTC
