### ISSUE TITLE
[Bug] Budgie applications menu applet ignores .menu overrides from ~/.config/menus/gnome-applications.menu

### ISSUE THREAD

**Issue by mgrouch** [BuddiesOfBudgie/budgie-desktop#507] opened 2024-01-16 05:14 UTC
### Description

Budgie applications menu applet ignores .menu overrides from ~/.config/menus/gnome-applications.menu

````
set | grep XDG
XDG_CONFIG_HOME=/home/user/.config
XDG_CURRENT_DESKTOP=Budgie:GNOME
XDG_DATA_DIRS=/usr/share/gnome:/usr/local/share/:/usr/share/
XDG_MENU_PREFIX=gnome-
XDG_RUNTIME_DIR=/run/user/1000
XDG_SESSION_CLASS=user
XDG_SESSION_TYPE=x11
    local -a dirs=(${BASH_COMPLETION_USER_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/bash-completion}/completions);
    for dir in ${XDG_DATA_DIRS:-/usr/local/share:/usr/share};
````

### Budgie version

10.7.1

### Operating System

Raspberry Pi Bookworm

### Steps to reproduce the issue

create ~/.config/menus/gnome-applications.menu

by copying /etc/xdg/menus/gnome-applications.menu

edit  ~/.config/menus/gnome-applications.menu to remove some sections.

### Actual result

menu changes are not reflected

### Expected result

menu changes are reflected

**Comment by JoshStrobl** [comment] 2024-01-16 07:52
Duplicate of #506

**Closed by JoshStrobl** 2024-01-16 07:52 UTC
