### ISSUE TITLE
[Request] Taskbar on second screen

### ISSUE THREAD

**Issue by ramzes800** [BuddiesOfBudgie/budgie-desktop#557] opened 2024-04-10 18:41 UTC
### Budgie version

10.9.1

### Use-cases

- Option to enable second taskbar on external screen while having one on primary display - now it's only possible to have it on primary display.
- Can open and manage apps from both panels  
- Can disable second taskbar

### Proposal

![Snapshot_2024-04-10_20-20-213](https://github.com/BuddiesOfBudgie/budgie-desktop/assets/134535089/c9f7819d-b9aa-400e-981a-2d531dca51d5)

**Comment by serebit** [comment] 2024-04-10 22:16
Duplicate of #289.

**Closed by serebit** 2024-04-10 22:16 UTC
