### ISSUE TITLE
[Request] Automatic focus on last used window on switch workspaces

### ISSUE THREAD

**Issue by icunhacorrea** [BuddiesOfBudgie/budgie-desktop#345] opened 2023-04-05 12:44 UTC
### Budgie version

10.7.1

### Use-cases

Hi!

I use multiple workspaces in budgie and i notice that on switch betwen then, i need use alt +  tab to select some window. It's the same in workspaces with a unique window.

Others desktop environments can focus directly on the last used window and this improve my workflow a lot during my day.

It's possible make something like that in future budgie versions? Exists a workaround to do this?

Thanks a lot!

### Proposal

Automatic select the last used window on switch betwen the workspaces.

**Comment by JoshStrobl** [comment] 2023-04-05 13:05
Duplicate of #321, bugs in Mutter related to focus issues on workspace change.

**Closed by JoshStrobl** 2023-04-05 13:05 UTC
