### ISSUE TITLE
[Bug] Changing Scale setting does not actually change scale

### ISSUE THREAD

**Issue by leftovercode** [BuddiesOfBudgie/budgie-desktop#616] opened 2024-09-22 01:03 UTC
### Description

Changing Scale in Displays settings does not change anything but the size of the mouse cursor.

### Budgie version

10.9.2

### Operating System

Arch Linux

### Steps to reproduce the issue

1. Set Scale setting in Displays tab to any value
2. Apply
3. See only mouse cursor changes size

### Actual result

![image](https://github.com/user-attachments/assets/5403b10c-9b3b-4278-ba45-121f417295c0)

![image](https://github.com/user-attachments/assets/8f886ad7-7413-4ec7-a3a0-b14487dccd45)

### Expected result

Scale to actually change and be applied to all windows

### Additional information

Since I have a 4K screen, I had set Scale to 200% with no issue. However, upon a recent update that included some gnome stuff, rebooting, and logging in everything was really small again, as if it was set to 100%. Changing the Scale value in the settings did nothing. I was only able to resolve this issue by using the following command:

`gsettings set org.gnome.settings-daemon.plugins.xsettings overrides "[{'Gdk/WindowScalingFactor', <2>}]"`

However, that has caused some weird issues where non-gnome apps reduce the mouse cursor size.

![image](https://github.com/user-attachments/assets/f49a5eb9-c4b7-4bc5-8da6-bee3ea828b25)

Before my most recent update, everything scaled and worked fine

**Comment by EbonJaeger** [comment] 2024-09-22 01:26
Duplicate of https://github.com/BuddiesOfBudgie/magpie/issues/32. Closing this issue in favor of the linked one to keep everything in one place.

**Closed by EbonJaeger** 2024-09-22 01:26 UTC
