### ISSUE TITLE
App icons remaining in Icon Task List after the app has been exited/killed

### ISSUE THREAD

**Issue by samteezy** [BuddiesOfBudgie/budgie-desktop#109] opened 2022-04-12 12:45 UTC
## Description
Some particular apps' icons don't disappear from the icon task list after the app has been exited. I've got a screenshot attached. Both Steam and the image viewer aren't actually running (confirmed by searching running processes).

## Budgie version
10.6.1

## Operating system
Solus (up to date)

## Steps to reproduce the issue
On Solus, open Steam (natively installed one). Exit it. Icon will remain in task list.

## Actual result
![image](https://user-images.githubusercontent.com/879186/162965142-f91a7d37-910e-4f5a-81a7-990f65fee243.png)

## Expected result
The Steam icon and gray icon next to it (I think it was from image viewer?) shouldn't be there.

## Additional information
Right clicking the Steam icon shows the regular context menu, but you can't select Close All Windows.
![image](https://user-images.githubusercontent.com/879186/162965342-ef17faed-41c4-4040-9fc5-e9b580e93df0.png)

**Comment by 0x199x** [comment] 2022-04-13 02:59
If it helps, I've had it happen with 3 applications so far: Steam, Discord (the loading dialog causes it), and [Synfig Studio](https://github.com/synfig/synfig/)

**Comment by serebit** [comment] 2022-04-13 19:39
This is something that we've been seeing intermittently, and that may have been fixed in master already. What are your Icon Tasklist settings?

**Comment by samteezy** [comment] 2022-04-13 20:15
All the toggles for Icon Task List are off _except_ for "Restrict to Workspace".

**Comment by 0x199x** [comment] 2022-04-16 02:09
> This is something that we've been seeing intermittently, and that may have been fixed in master already. What are your Icon Tasklist settings?

This seems to be fixed for me now.  Tested Synfig and Discord.. no more phantom icons.  

And if it matters at this point... all available icon task list settings are switched off for me.

**Comment by serebit** [comment] 2022-04-17 21:45
So neither of you have window grouping enabled? We're going to be removing that option in v10.7 (window grouping will be force enabled and we'll have a new Tasklist for those who don't like window grouping), and we have a couple commits that could maybe fix this issue in the meantime if we decide to release a new bugfix version for v10.6. I'll close this for now, but if you're still seeing this after we release a new version of Budgie (whether v10.6.2 or v10.7), comment here and I'll reopen the issue.

**Closed by serebit** 2022-04-17 21:45 UTC
Labels: bug

**Comment by 0x199x** [comment] 2022-04-22 13:30
> So neither of you have window grouping enabled? We're going to be removing that option in v10.7 (window grouping will be force enabled and we'll have a new Tasklist for those who don't like window grouping), and we have a couple commits that could maybe fix this issue in the meantime if we decide to release a new bugfix version for v10.6. I'll close this for now, but if you're still seeing this after we release a new version of Budgie (whether v10.6.2 or v10.7), comment here and I'll reopen the issue.

Nope, never been a fan of window grouping.  I haven't had any more trouble with icons getting stuck.  All is well. 

If I may.. why two task lists applets instead of just one with configuration options? The tasklist/icontasklist thing has always seemed a bit redundant to me. I thought I remembered eons ago in the Ikey days that there was some discussion about merging them

**Comment by serebit** [comment] 2022-04-22 15:43
Ideally we'd keep both non-grouping and grouping in one applet, but it's proven to be an absolute nightmare to maintain. Fixing an issue with the grouping mode often breaks something in the non-grouping mode, and vice versa. We've decided that keeping the modes separate is the best option in the interest of stability and ease of maintenance.

**Comment by solomongrundy6** [comment] 2022-07-30 04:17
I have also had this happen with mpv, which was one of the apps that was previously having the bug where it would not show any icon in the taskbar.  I do have window grouping on, and if it's relevant the times that it has happened to me were when it was spawned by a bash script.  It isn't 100% reproducible for me.  Right-clicking on the icon and pinning then unpinning it gets rid of it.
