### ISSUE TITLE
[Bug] Keyboard layout switcher crashes Budgie session 

### ISSUE THREAD

**Issue by tomasarad** [BuddiesOfBudgie/budgie-desktop#441] opened 2023-09-03 19:01 UTC
### Description

Hi!
On budgie 10.8 (on Sparky Linux, Spiral Linux -both Debian based and on Gecko Tumbleweed - opensuse based ) if I put the layout switcher on panel, will crash the whole session, I not find any other fix then login with other DE run 'Budgie Desktop Settings' and remove the keyboard layout switcher - but I need this switcher. (I use en, ro, hu language, but don't think the language is a problem)
I hope you will find some way to fix it. I wish you all the best!
Thank you! 
with all my respect tomasarad

### Budgie version

10.8

### Operating System

Gecko Linux, Sparky Linux, Spiral Linux

### Steps to reproduce the issue

1. go to 'Budgie Desktop Settings'
2. go to 'dock'
3. add applet -> choose 'Keyboard layout'
4. soon after the applet is added the session will crash 'can't recover' message

### Actual result

session crash

### Expected result

session crash

**Comment by serebit** [comment] 2023-09-03 19:10
Duplicate of #319.

**Closed by serebit** 2023-09-03 19:10 UTC
