### ISSUE TITLE
[Bug] Adding the Keyboard Layout applet causes the DE to fail

### ISSUE THREAD

**Issue by AKotov-dev** [BuddiesOfBudgie/budgie-desktop#319] opened 2023-02-24 18:53 UTC
### Description

Hello.
Budgie Desktop-10.7.1, Mageia-9.

**Problem:**
If you add the `Keyboard Layout` applet to the bottom panel and reboot, the panel no longer loads and the system hangs: the hard disk arrives in some kind of write/read cycle, the keyboard does not work. The only method is the system `Reset` button.

Best regards,
Alex

### Budgie version

budgie-desktop 10.7.1

### Operating System

Mageia-9

### Steps to reproduce the issue

Add the `Keyboard Layout` applet and restart your computer.

### Actual result

DE does not load.

### Expected result

The DE is supposed to boot sometime.

**Comment by serebit** [comment] 2023-02-24 20:44
Can you reproduce this by relogging after adding the applet (i.e. log out and log back in) or is it only when rebooting?

**Comment by AKotov-dev** [comment] 2023-02-24 21:16
After log out and re-entry, the mouse and keyboard do not work. That is, the effect is about the same, except that now I see the bottom panel, but mouse clicks on it do not work.

**Comment by baraclese** [comment] 2023-02-25 00:40
I believe I encountered the same bug on arch linux with the update from ibus 1.5.27 to 1.5.28, downgrading ibus (and libibus) to 1.5.27 fixed the problem.

**Comment by serebit** [comment] 2023-02-25 17:13
Of course it's ibus...

**Comment by fossfreedom** [comment] 2023-02-25 17:47
Please can affected people describe their keyboard layouts. What are they? Are you using ibus? If so what is your ibus setup? Basically we need more info to be able to reproduce this.

As an aside we have .28 on ubuntu and we haven't noticed any  issues with en_US

**Comment by serebit** [comment] 2023-02-25 19:00
I can't reproduce this on Arch with ibus .28.

**Comment by AKotov-dev** [comment] 2023-02-25 20:16
Guys, this may seem strange... But having QEMU on hand and the ability to create/use several clones of already installed/configured systems with Budgie-10.7.1 without the `Keyboard Layout` applet, after destroying another unsuccessful copy, I found out that if you add not only a single `Keyboard Layout` to the panel, but also the `Night Light` applet with it, **then everything works after exit/login and after reboot**. However, if you delete the `Night Light` applet and leave only the `Keyboard Layout`, then DE does not load again (see screenshot).

![Snapshot_2023-02-25_22-53-46](https://user-images.githubusercontent.com/74963267/221377601-89921645-6cbb-4e26-b591-17cb5871a3bc.png)

I understand that it looks silly from my side, but maybe it will give you some thoughts... :)

p.s. `Keyboard Layout` = [EN/RU].

Sincerely,
Alex

**Comment by baraclese** [comment] 2023-02-25 22:30
Keyboard Layouts are US and Japanese (with ibus-kkc). I use a panel which has this structure: 
![Snapshot_top_panel](https://user-images.githubusercontent.com/1628879/221382404-dd1c03de-6ac2-4210-8420-1f2c9f125487.png)

**Comment by fossfreedom** [comment] 2023-02-27 10:59
'fraid still cannot reproduce with the above two instruction variants on Ubuntu lunar.

When you have the DE issues please can you switch to a TTY (CTRL+ALT+F3), login and run

    journalctl -ae --full

Use the arrow keys to move around - see if there are any obvious issues around the time of the DE failures - usually the text will be in either yellow or red.

**Comment by AKotov-dev** [comment] 2023-02-27 15:10
Additionally, I tested Budgie-10.7.1 in Fedora-37 and everything works there, there are no problems. I tend to think that something else has not been fully updated in Mageia-9. Nothing else comes to mind... I installed the two applets I wrote about above. For now I will work like this. And I also could not get the journalctl output due to the system freezing. :(

**Comment by fossfreedom** [comment] 2023-02-28 00:00
The only thing I can think of here is to install the debug symbols for budgie-desktop using whatever instructions are relevant to your distro

Then using gdb to attach to the `budgie-panel --replace` running process and watch for whatever is basically spinning out of control

https://stackoverflow.com/questions/2308653/can-i-use-gdb-to-debug-a-running-process

**Comment by AKotov-dev** [comment] 2023-02-28 08:08
@fossfreedom

Thanks. In the meantime, here, I managed to take a screenshot when starting `budgie-desktop --replace &!` from IceWM with `Keyboard Layout` installed:

![1](https://user-images.githubusercontent.com/74963267/221789721-8976a613-d5ad-436e-bec7-6fab5e7c28de.png)

Then I launch from the `Menu-IBus Settings`. It outputs a warning that `IBus is not being executed. Run it?`. I press `Yes` and `Keyboard Layout` **starts working and switching input languages and works well**. He also suggests adding some lines to $HOME/.bashrc:

![2](https://user-images.githubusercontent.com/74963267/221789802-c18733cb-443c-44aa-a76a-2da9e2cdae46.png)

After adding these lines and restarting the computer, I see that `ibus` is not running and I start it and start it again `budgie-desktop --replace &!`

![3](https://user-images.githubusercontent.com/74963267/221789850-bde7078a-e25d-4932-9240-7ac093a88013.png)

The result is that everything freezes again and the hard disk is constantly in a write/read cycle. After some time, the panel disappears altogether. What conclusions can be drawn from this? Thanks.

**Comment by AKotov-dev** [comment] 2023-02-28 09:05
**Additionally:** 

If you run `ibus` **after** the `budgie-panel` starts, then **everything works fine**, and if **before** the `budgie-panel` starts, then everything **freezes**.

In other words - it looks like this (I have problems with English, sorry, I'd rather show you):

So - `Keyboard Layout` starts and works well:
```
budgie-panel --replace & sleep 3 && ibus-daemon -d
```
...killing processes (cleaning for the test)
```
killall budgie-panel ibus
```
So (starting in reverse order) - the computer freezes and everything freezes:
```
ibus-daemon -d && sleep 3 && budgie-panel --replace &!
```
Maybe it will come in handy? Thanks.

**Comment by fossfreedom** [comment] 2023-02-28 09:49
ibus-daemon  is started by budgie-wm - https://github.com/BuddiesOfBudgie/budgie-desktop/blob/main/src/wm/ibus.vala#L76 -  The fact that you have had to start ibus-daemon before the panel is worrying.

Is there anything in the journal ibus related?

    journalctl -ae | grep -i ibus

if you kill ibus-daemon and start it up again using the parameters budgie currently expect are there any errors/warning reported?

    ibus-daemon --xim --panel disable

**Comment by AKotov-dev** [comment] 2023-02-28 11:19
I started `journalctl -f` (in real time in a separate terminal) and after about 2 minutes of waiting, this came out. Is that by any chance the wrong thing? :)

![portal IBus](https://user-images.githubusercontent.com/74963267/221837911-43be6236-98da-4207-8f14-371b9803d191.png)

That is:
**dbus-daemon[1411]: [session uid=1411] Failed to activate service 'org.freedesktop.portal.IBus': time out (service_start_time out=12000ms)**

**Comment by fossfreedom** [comment] 2023-02-28 11:24
"current session already has an ibus-daemon"

Did you check and kill all ibus related processes first? Use `ps -ef | grep -i ibus`

Worth also checking the output of that command carefully to see how the current ibus processes have been initiated before killing them.

I think we need to see the output of this to see what happens on login

    journalctl -ae | grep -i ibus

**Comment by AKotov-dev** [comment] 2023-02-28 12:18
oops... ok...
With this parameter `ibus-daemon --xim --panel disable`:

![222](https://user-images.githubusercontent.com/74963267/221852088-6235cd24-19a2-4b55-b283-c9d55914d189.png)

Now, if you run everything at once...
```
killall budgie-panel ibus-daemon
ibus-daemon --xim --panel disable & sleep 3 && budgie-panel --replace &!
```
...then again everything hangs and the log is not output, a complete freeze of the system:

![333](https://user-images.githubusercontent.com/74963267/221852151-475f560a-147d-4481-861b-1c975af661f8.png)

And after about 5 minutes:
```
1987 Killed              budgie-panel --replace
```

**Comment by fossfreedom** [comment] 2023-02-28 12:26
![image](https://user-images.githubusercontent.com/996240/221853720-a212615b-57e9-4179-9cb6-789b56f1e332.png)

That shows other budgie elements are not running as well.

Please confirm you are actually using lightdm with slick-greeter as your login manager.  i.e. you are not using GDM3.

**Comment by AKotov-dev** [comment] 2023-02-28 12:44
I used `lxdm`. Right now I have installed `lightdm` and have already logged in through it. The result has not changed. By the way, Fedora-37 uses GDM and there are no problems. Is `lightdm` a prerequisite for Budgie? Then how to explain that Budgie is 10.6.4 + `lxdm` works now, if you install it?

**Comment by AKotov-dev** [comment] 2023-03-01 06:27
See: https://pkgs.org/search/?q=ibus

I suspect that Fedora-37 + Budgie-10.7.1 works because ibus-1.5.27 is installed in it. Let me remind you that in Mageia-9 ibus-1.5.28. By the way, in Ubuntu 22.04 LTS (Jammy Jellyfish) maximum version = ibus-1.5.26.

Now I will try to install ArchLinux (+ ArchLinux Extra x86_64 repo) with ibus-1.5.28 + `Keyboard Layout` with two input languages. With this I want to confirm or refute **baraclese's** theory about the upcoming regression.

Please, wait for the test results. Thanks...

**Comment by AKotov-dev** [comment] 2023-03-01 09:05
**Test results in Arch Linux-2023.02.01 (ibus-1.5.28-1)**

The version with a downgrade to ibus-1.5.27 for Arch Linux-2023.02.01 is not confirmed (see screenshot). In Arch Linux-2023.02.01 (ibus-1.5.28-1) `Keyboard Layout` switches languages perfectly and there are no problems with loading and freezing the system.

![ArchLinux-2023 02 01_Clone2-RU](https://user-images.githubusercontent.com/74963267/222092323-d358e161-b4b9-4cdd-a135-09a1f44bda33.png)

I have no more questions for the developers. Thank you all very much for the consultations provided. If you deem it necessary, this bug can be closed.

Sincerely,
Alex

**Comment by baraclese** [comment] 2023-03-01 11:36
Today I have some time to look into this and installed a VM with Arch Linux. I was able to reproduce the error with the following setup:
prerequisite:
- in /etc/locale.gen enable en_US.UTF-8 and ja_JP.UTF-8
- run locale-gen
setup budgie:
- add 'Keyboard Layout' plugin
- open Budgie Control Center go to Region & Language, click Formats and set All Formats to Japanese (日本).
- log out and log in again

**Comment by baraclese** [comment] 2023-03-01 13:07
I bisected ibus to this first bad commit: https://github.com/ibus/ibus/commit/19ca10651890ce0d88ec613de0e8930090105dc8

**Comment by serebit** [comment] 2023-03-01 14:09
So the question remains, is this an ibus bug or a Budgie bug?

**Comment by NeWolf1** [comment] 2023-06-19 10:10
Keyboard layout doesn't seem to be relevant.
I have only US keyboard layout and locale.conf, locale.gen is set to en_GB.UTF-8

**Comment by stereotypy** [comment] 2023-09-18 00:14
Found out this is what was causing the segfault here: https://github.com/BuddiesOfBudgie/budgie-desktop/issues/441

This was introduced with the Budgie  10.8 update for me. People clearly still having issues with this recently around the update such as here: https://github.com/BuddiesOfBudgie/budgie-desktop/issues/441 and here: https://forum.endeavouros.com/t/keyboard-layout-applet-breaks-budgie/44245

@EbonJaeger @JoshStrobl looks like the fix still hasn't resolved it for folks.

This broke things so badly for me that I had to run `dconf reset -f /com/solus-project/budgie-panel/` instead of the regular nohup command.

**Comment by serebit** [comment] 2023-10-16 20:08
Is this still happening? If it is, can you follow the steps in https://docs.buddiesofbudgie.org/developer/workflow/providing-backtraces so we can see where the segfault is occurring?

**Comment by AKotov-dev** [comment] 2023-12-27 08:21
Hello dear **serebit**. I apologize for the long absence of information on my part on this issue. I was forced to disable the notification service on my GitHub because some Polish schoolchildren were actively sending various naked women to my inbox (spam).

Regarding the issue, I can report the following: with the release of **Budgie-v10.8** there are no more problems and DE works stably. This allowed me to release the next builds of my [Mageia derivative](https://drive.google.com/drive/folders/174Cya1NIWOag4BRP0PYgXrT8Jtn1djym), which is designed to work with VPN/VPS in aggressive networks of countries with authoritarian form of government (Russia, China, Iran and others). So you can clearly see that Budgie-v10.8.2 is working.

![Budgie-v10 8 2-Proserpina](https://github.com/BuddiesOfBudgie/budgie-desktop/assets/74963267/8cd8890c-310d-4bb7-86b3-853ad148daec)

Thank you very much for your work. I congratulate everyone on the upcoming New Year, wish you good luck to all your projects and don’t say goodbye.

Sincerely,
Alex

**Comment by AKotov-dev** [comment] 2023-12-27 09:01
Additionally, regarding the question [full desktop crush after adding widgets #500](https://github.com/BuddiesOfBudgie/budgie-desktop/issues/500) (see above, **JoshStrobl** mentioned this issue), I would like to inform you that a common reason for logging out with the error shown there in the screenshot is hardware acceleration. If you remove the **gstreamer1.0-vaapi** package and reboot, i.e. use only software acceleration, then perhaps the problem should go away. I release my builds exclusively with software graphics acceleration, since it is unknown which card and drivers will be used. This is most likely a GNOME issue, but not certain.

Sincerely,
Alex

**Comment by AKotov-dev** [comment] 2024-04-28 16:04
Hello, dear **serebit** and **JoshStrobl**. I hasten to report that Budgie-v10.9.1 works great and the keyboard layout too.

![Budgie-10 9 1](https://github.com/BuddiesOfBudgie/budgie-desktop/assets/74963267/8ba98a64-9bb4-458b-8225-c56332b94f52)

For this version we had to additionally build a package for `budgie-session` instead of `gnome-session`. Today there are already: budgie-control-center, budgie-screensaver and budgie-session. Taking this opportunity, if you don’t mind, I would like to ask: in the future, do you plan to convert all dependencies with the `gnome-*` prefix to `budgie-*` (gnome-bluetooth, gnome-alsamixer, gnome-calculator, etc... )? I just don’t really understand the whole process, that’s why I had a question. Thank you.

Sincerely,
Alex

**Comment by JoshStrobl** [comment] 2024-04-28 17:21
No. Budgie 11 will not be based on GNOME and we have no plans at this time on forking more components developed by GNOME for Budgie 10 series.

You can read on why budgie-session exists at https://buddiesofbudgie.org/blog/budgie-10-9-released

**Closed** 2024-04-28 17:22 UTC
Labels: bug, needs-more-info

**Comment by oceanusxiv** [comment] 2025-10-26 17:08
It appears that I have this bug again with budgie 10.9.2. I get a segfault

```
Oct 26 09:57:53 eric-manjaro systemd-coredump[2794]: [🡕] Process 2730 (budgie-panel) of user 1000 dumped core.
                                                     
                                                     Stack trace of thread 2730:
                                                     #0  0x00007f2f0c399094 ibus_engine_desc_get_name (libibus-1.0.so.5 + 0x3b094)
                                                     #1  0x00007f2f0ff04621 n/a (libkeyboardlayoutapplet.so + 0x4621)
                                                     #2  0x00007f2f2c0491fc n/a (libgio-2.0.so.0 + 0xa81fc)
                                                     #3  0x00007f2f2c04ec52 n/a (libgio-2.0.so.0 + 0xadc52)
                                                     #4  0x00007f2f0c37ea3f n/a (libibus-1.0.so.5 + 0x20a3f)
                                                     #5  0x00007f2f2c0491fc n/a (libgio-2.0.so.0 + 0xa81fc)
                                                     #6  0x00007f2f2c04ec52 n/a (libgio-2.0.so.0 + 0xadc52)
                                                     #7  0x00007f2f2c0b7623 n/a (libgio-2.0.so.0 + 0x116623)
                                                     #8  0x00007f2f2c0491fc n/a (libgio-2.0.so.0 + 0xa81fc)
                                                     #9  0x00007f2f2c049245 n/a (libgio-2.0.so.0 + 0xa8245)
                                                     #10 0x00007f2f2be4a880 n/a (libglib-2.0.so.0 + 0x5e880)
                                                     #11 0x00007f2f2be4bcd7 n/a (libglib-2.0.so.0 + 0x5fcd7)
                                                     #12 0x00007f2f2be4c097 g_main_loop_run (libglib-2.0.so.0 + 0x60097)
                                                     #13 0x00007f2f2b96b88f gtk_main (libgtk-3.so.0 + 0x36b88f)
                                                     #14 0x0000557bd553e1f7 main (/usr/bin/budgie-panel + 0x111f7)
                                                     #15 0x00007f2f2b227675 n/a (libc.so.6 + 0x27675)
                                                     #16 0x00007f2f2b227729 __libc_start_main (libc.so.6 + 0x27729)
                                                     #17 0x0000557bd553e235 _start (/usr/bin/budgie-panel + 0x11235)
                                                     
                                                     Stack trace of thread 2732:
                                                     #0  0x00007f2f2b31876d syscall (libc.so.6 + 0x11876d)
                                                     #1  0x00007f2f2be7a8ee g_cond_wait (libglib-2.0.so.0 + 0x8e8ee)
                                                     #2  0x00007f2f2be11ebd n/a (libglib-2.0.so.0 + 0x25ebd)
                                                     #3  0x00007f2f2be11f2d g_async_queue_pop (libglib-2.0.so.0 + 0x25f2d)
                                                     #4  0x00007f2f2ade351c n/a (libpangoft2-1.0.so.0 + 0xc51c)
                                                     #5  0x00007f2f2be8297c n/a (libglib-2.0.so.0 + 0x9697c)
                                                     #6  0x00007f2f2b2969cb n/a (libc.so.6 + 0x969cb)
                                                     #7  0x00007f2f2b31aa0c n/a (libc.so.6 + 0x11aa0c)
                                                     
                                                     Stack trace of thread 2733:
                                                     #0  0x00007f2f2b31876d syscall (libc.so.6 + 0x11876d)
                                                     #1  0x00007f2f2be7a8ee g_cond_wait (libglib-2.0.so.0 + 0x8e8ee)
                                                     #2  0x00007f2f2be11ebd n/a (libglib-2.0.so.0 + 0x25ebd)
```

When adding the keyboard layout applet in budgie panel.

The budgie-panel prints

```
(budgie-panel:2730): GLib-GObject-CRITICAL **: 09:57:52.436: g_object_ref_sink: assertion 'G_IS_OBJECT (object)' failed

(budgie-panel:2730): IBUS-CRITICAL **: 09:57:52.436: ibus_serializable_deserialize_object: assertion 'g_type_is_a (type, IBUS_TYPE_SERIALIZABLE)' failed
```

before segfaulting.

For reference here is my package versions.
```
Name                  : budgie-desktop
Version               : 10.9.2-3
Description           : A familiar, modern desktop environment
URL                   : https://github.com/BuddiesOfBudgie/budgie-desktop
Licenses              : GPL-2.0-only AND LGPL-2.1-only
Repository            : extra
Installed Size        : 6.1 MB
Groups                : budgie
Depends On            : accountsservice budgie-control-center budgie-screensaver budgie-session gnome-themes-standard ibus libgee libpeas libwnck3 libxfce4windowing magpie-wm xdg-desktop-portal-gtk zenity
Optional Dependencies : budgie-desktop-view: Desktop icons [Installed]
                        budgie-backgrounds: Default background set [Installed]
                        network-manager-applet: Network management in the panel [Installed]
                        power-profiles-daemon: Manage power and performance from the panel
                        switcheroo-control: Open apps with the secondary GPU
Required By           : budgie-extras manjaro-budgie-settings
Optional For          : --
Provides              : --
Replaces              : --
Conflicts With        : --
Packager              : Campbell Jones <serebit@archlinux.org>
Build Date            : Tue 25 Mar 2025 09:22:35 AM PDT
Install Date          : Sun 26 Oct 2025 09:52:25 AM PDT
Install Reason        : Explicitly installed
Validated By          : Signature
Backup files          : --

Name                  : ibus
Version               : 1.5.32-1
Description           : Intelligent input bus for Linux/Unix
URL                   : https://github.com/ibus/ibus/wiki
Licenses              : LGPL-2.1-or-later
Repository            : extra
Installed Size        : 118.9 MB
Groups                : --
Depends On            : at-spi2-core cairo dconf gdk-pixbuf2 glib2 graphene gtk3 gtk4 hicolor-icon-theme libdbusmenu-glib libdbusmenu-gtk3 libnotify libx11 libxkbcommon libxfixes libxi pango python
                        python-gobject wayland libibus=1.5.32
Optional Dependencies : --
Required By           : budgie-control-center budgie-desktop ibus-libpinyin
Optional For          : --
Provides              : --
Replaces              : --
Conflicts With        : --
Packager              : Campbell Jones <serebit@archlinux.org>
Build Date            : Tue 08 Apr 2025 07:42:24 PM PDT
Install Date          : Fri 17 Oct 2025 01:02:49 AM PDT
Install Reason        : Installed as a dependency for another package
Validated By          : Signature
Backup files          : --
```
